[book]
authors = ["Linyu Wu", "Lau YeeYu"]
language = "zh-CN"
multilingual = true
src = "src"
title = "ACore Guide"

[output.html]
git-repository-url = "https://github.com/celve/acore-guide"
git-repository-icon = "fa-github"
mathjax-support = true

[output.html.playground]
runnable = false
